import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { QueryClient, QueryClientProvider } from "react-query";
import Providers from "@/external/providers";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {},
          components: {
            Card: {
              headerBg: "#b5f5ec",
            },
          },
        }}
      >
        <Providers>
          <Navbar>
            <body className={inter.className}>{children}</body>
          </Navbar>
        </Providers>
      </ConfigProvider>
    </html>
  );
}
