name: Linting

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint   # Assuming your linting script is named 'lint'
      - name: Fail workflow if there are linting errors
        run: exit code=${?} && [ "$code" = "0" ] || exit 1
